//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskasWorkFlowApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskasWorkFlowAppEntities2 : DbContext
    {
        public TaskasWorkFlowAppEntities2()
            : base("name=TaskasWorkFlowAppEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<ParameterRuns> ParameterRuns { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<ParentChildTaska> ParentChildTaska { get; set; }
        public virtual DbSet<ParentChildTaskaRun> ParentChildTaskaRun { get; set; }
        public virtual DbSet<TaskaRuns> TaskaRuns { get; set; }
        public virtual DbSet<Taskas> Taskas { get; set; }
    }
}
