//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskasWorkFlowApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentChildTaska
    {
        public int ChildTaskaId { get; set; }
        public int ParentTaskaId { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Taskas Taskas { get; set; }
        public virtual Taskas Taskas1 { get; set; }
    }
}
