//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskasWorkFlowApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskaRunChilds
    {
        public int ParentTaskaRunId { get; set; }
        public int ChildTaskaRunId { get; set; }
        public int Order { get; set; }
    
        public virtual TaskaRuns TaskaRuns { get; set; }
        public virtual TaskaRuns TaskaRuns1 { get; set; }
    }
}
