// <auto-generated />
namespace TaskWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_TaskaId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_TaskaId));
        
        string IMigrationMetadata.Id
        {
            get { return "201607192234061_update_TaskaId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
